RMarkdown: MBMS_Analysis_Reliability
Author: Zoe Crawley
Date: 02/10/2022
Data: MBMS Phase 1 Data, ZC Honor's Thesis

In this document I will calculate reliability for the following measures: PSS, RYFF, BDI-II, BAI, and PANAS.

```{r}
library(readr)
library(ltm)
```

*PSS*
```{r}
#load dataset
pss_baseline <- read_csv("thesis/reliability/mbms_pssreliability_baseline.csv")
pss_post <- read_csv("thesis/reliability/mbms_pssreliability_post.csv")
pss_followup <- read_csv("thesis/reliability/mbms_pssreliability_followup.csv")
> 
```


```{r}
#calculate baseline
pss_baseline <- t(pss_baseline)
cronbach.alpha(pss_baseline)

#calculate post
pss_post <- t(pss_post)
cronbach.alpha(pss_post)

#calculate follow-up
pss_followup <- t(mbms_pssreliability_followup)
cronbach.alpha(pss_followup)

```

*RYFF*
```{r}
#load dataset#
ryff_baseline <- read_csv("thesis/reliability/mbms_ryffreliability_baseline.csv")
ryff_post <- read_csv("thesis/reliability/mbms_ryffreliability_post.csv")
ryff_followup <- read_csv("thesis/reliability/mbms_ryffreliability_followup.csv")
```

```{r}
#calculate baseline
ryff_baseline <- t(ryff_baseline)
cronbach.alpha(ryff_baseline)

#calculate post
ryff_post <- t(ryff_post)
cronbach.alpha(ryff_post)

#calculate follow-up
ryff_followup <- t(ryff_followup)
cronbach.alpha(ryff_followup)

```
```

